# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marigov/Documents/Simulator_Release_170110/Client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marigov/Documents/Simulator_Release_170110/Client

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(CMAKE_COMMAND) -E cmake_progress_start /Users/marigov/Documents/Simulator_Release_170110/Client/CMakeFiles /Users/marigov/Documents/Simulator_Release_170110/Client/applications/CMakeFiles/progress.marks
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marigov/Documents/Simulator_Release_170110/Client/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
applications/CMakeFiles/task1_2.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/task1_2.dir/rule
.PHONY : applications/CMakeFiles/task1_2.dir/rule

# Convenience name for target.
task1_2: applications/CMakeFiles/task1_2.dir/rule

.PHONY : task1_2

# fast build rule for target.
task1_2/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_2.dir/build.make applications/CMakeFiles/task1_2.dir/build
.PHONY : task1_2/fast

# Convenience name for target.
applications/CMakeFiles/spinLeftRight.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/spinLeftRight.dir/rule
.PHONY : applications/CMakeFiles/spinLeftRight.dir/rule

# Convenience name for target.
spinLeftRight: applications/CMakeFiles/spinLeftRight.dir/rule

.PHONY : spinLeftRight

# fast build rule for target.
spinLeftRight/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/spinLeftRight.dir/build.make applications/CMakeFiles/spinLeftRight.dir/build
.PHONY : spinLeftRight/fast

# Convenience name for target.
applications/CMakeFiles/task1_1.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/task1_1.dir/rule
.PHONY : applications/CMakeFiles/task1_1.dir/rule

# Convenience name for target.
task1_1: applications/CMakeFiles/task1_1.dir/rule

.PHONY : task1_1

# fast build rule for target.
task1_1/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_1.dir/build.make applications/CMakeFiles/task1_1.dir/build
.PHONY : task1_1/fast

# Convenience name for target.
applications/CMakeFiles/task1_0.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/task1_0.dir/rule
.PHONY : applications/CMakeFiles/task1_0.dir/rule

# Convenience name for target.
task1_0: applications/CMakeFiles/task1_0.dir/rule

.PHONY : task1_0

# fast build rule for target.
task1_0/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_0.dir/build.make applications/CMakeFiles/task1_0.dir/build
.PHONY : task1_0/fast

# Convenience name for target.
applications/CMakeFiles/task1_3.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/task1_3.dir/rule
.PHONY : applications/CMakeFiles/task1_3.dir/rule

# Convenience name for target.
task1_3: applications/CMakeFiles/task1_3.dir/rule

.PHONY : task1_3

# fast build rule for target.
task1_3/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_3.dir/build.make applications/CMakeFiles/task1_3.dir/build
.PHONY : task1_3/fast

spinLeftRight.o: spinLeftRight.c.o

.PHONY : spinLeftRight.o

# target to build an object file
spinLeftRight.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/spinLeftRight.dir/build.make applications/CMakeFiles/spinLeftRight.dir/spinLeftRight.c.o
.PHONY : spinLeftRight.c.o

spinLeftRight.i: spinLeftRight.c.i

.PHONY : spinLeftRight.i

# target to preprocess a source file
spinLeftRight.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/spinLeftRight.dir/build.make applications/CMakeFiles/spinLeftRight.dir/spinLeftRight.c.i
.PHONY : spinLeftRight.c.i

spinLeftRight.s: spinLeftRight.c.s

.PHONY : spinLeftRight.s

# target to generate assembly for a file
spinLeftRight.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/spinLeftRight.dir/build.make applications/CMakeFiles/spinLeftRight.dir/spinLeftRight.c.s
.PHONY : spinLeftRight.c.s

task1_0.o: task1_0.c.o

.PHONY : task1_0.o

# target to build an object file
task1_0.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_0.dir/build.make applications/CMakeFiles/task1_0.dir/task1_0.c.o
.PHONY : task1_0.c.o

task1_0.i: task1_0.c.i

.PHONY : task1_0.i

# target to preprocess a source file
task1_0.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_0.dir/build.make applications/CMakeFiles/task1_0.dir/task1_0.c.i
.PHONY : task1_0.c.i

task1_0.s: task1_0.c.s

.PHONY : task1_0.s

# target to generate assembly for a file
task1_0.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_0.dir/build.make applications/CMakeFiles/task1_0.dir/task1_0.c.s
.PHONY : task1_0.c.s

task1_1.o: task1_1.c.o

.PHONY : task1_1.o

# target to build an object file
task1_1.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_1.dir/build.make applications/CMakeFiles/task1_1.dir/task1_1.c.o
.PHONY : task1_1.c.o

task1_1.i: task1_1.c.i

.PHONY : task1_1.i

# target to preprocess a source file
task1_1.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_1.dir/build.make applications/CMakeFiles/task1_1.dir/task1_1.c.i
.PHONY : task1_1.c.i

task1_1.s: task1_1.c.s

.PHONY : task1_1.s

# target to generate assembly for a file
task1_1.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_1.dir/build.make applications/CMakeFiles/task1_1.dir/task1_1.c.s
.PHONY : task1_1.c.s

task1_2.o: task1_2.c.o

.PHONY : task1_2.o

# target to build an object file
task1_2.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_2.dir/build.make applications/CMakeFiles/task1_2.dir/task1_2.c.o
.PHONY : task1_2.c.o

task1_2.i: task1_2.c.i

.PHONY : task1_2.i

# target to preprocess a source file
task1_2.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_2.dir/build.make applications/CMakeFiles/task1_2.dir/task1_2.c.i
.PHONY : task1_2.c.i

task1_2.s: task1_2.c.s

.PHONY : task1_2.s

# target to generate assembly for a file
task1_2.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_2.dir/build.make applications/CMakeFiles/task1_2.dir/task1_2.c.s
.PHONY : task1_2.c.s

task1_3.o: task1_3.c.o

.PHONY : task1_3.o

# target to build an object file
task1_3.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_3.dir/build.make applications/CMakeFiles/task1_3.dir/task1_3.c.o
.PHONY : task1_3.c.o

task1_3.i: task1_3.c.i

.PHONY : task1_3.i

# target to preprocess a source file
task1_3.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_3.dir/build.make applications/CMakeFiles/task1_3.dir/task1_3.c.i
.PHONY : task1_3.c.i

task1_3.s: task1_3.c.s

.PHONY : task1_3.s

# target to generate assembly for a file
task1_3.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/task1_3.dir/build.make applications/CMakeFiles/task1_3.dir/task1_3.c.s
.PHONY : task1_3.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... task1_2"
	@echo "... spinLeftRight"
	@echo "... task1_1"
	@echo "... task1_0"
	@echo "... task1_3"
	@echo "... spinLeftRight.o"
	@echo "... spinLeftRight.i"
	@echo "... spinLeftRight.s"
	@echo "... task1_0.o"
	@echo "... task1_0.i"
	@echo "... task1_0.s"
	@echo "... task1_1.o"
	@echo "... task1_1.i"
	@echo "... task1_1.s"
	@echo "... task1_2.o"
	@echo "... task1_2.i"
	@echo "... task1_2.s"
	@echo "... task1_3.o"
	@echo "... task1_3.i"
	@echo "... task1_3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

