# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marigov/Documents/Simulator_Release_170110/Client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marigov/Documents/Simulator_Release_170110/Client

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(CMAKE_COMMAND) -E cmake_progress_start /Users/marigov/Documents/Simulator_Release_170110/Client/CMakeFiles /Users/marigov/Documents/Simulator_Release_170110/Client/applications/CMakeFiles/progress.marks
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marigov/Documents/Simulator_Release_170110/Client/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
applications/CMakeFiles/teslaCarlo.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/teslaCarlo.dir/rule
.PHONY : applications/CMakeFiles/teslaCarlo.dir/rule

# Convenience name for target.
teslaCarlo: applications/CMakeFiles/teslaCarlo.dir/rule

.PHONY : teslaCarlo

# fast build rule for target.
teslaCarlo/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/teslaCarlo.dir/build.make applications/CMakeFiles/teslaCarlo.dir/build
.PHONY : teslaCarlo/fast

# Convenience name for target.
applications/CMakeFiles/tesla.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/tesla.dir/rule
.PHONY : applications/CMakeFiles/tesla.dir/rule

# Convenience name for target.
tesla: applications/CMakeFiles/tesla.dir/rule

.PHONY : tesla

# fast build rule for target.
tesla/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/tesla.dir/build.make applications/CMakeFiles/tesla.dir/build
.PHONY : tesla/fast

# Convenience name for target.
applications/CMakeFiles/sensor.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/sensor.dir/rule
.PHONY : applications/CMakeFiles/sensor.dir/rule

# Convenience name for target.
sensor: applications/CMakeFiles/sensor.dir/rule

.PHONY : sensor

# fast build rule for target.
sensor/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/sensor.dir/build.make applications/CMakeFiles/sensor.dir/build
.PHONY : sensor/fast

# Convenience name for target.
applications/CMakeFiles/wall.dir/rule:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/CMakeFiles/wall.dir/rule
.PHONY : applications/CMakeFiles/wall.dir/rule

# Convenience name for target.
wall: applications/CMakeFiles/wall.dir/rule

.PHONY : wall

# fast build rule for target.
wall/fast:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/wall.dir/build.make applications/CMakeFiles/wall.dir/build
.PHONY : wall/fast

sensor.o: sensor.c.o

.PHONY : sensor.o

# target to build an object file
sensor.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/sensor.dir/build.make applications/CMakeFiles/sensor.dir/sensor.c.o
.PHONY : sensor.c.o

sensor.i: sensor.c.i

.PHONY : sensor.i

# target to preprocess a source file
sensor.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/sensor.dir/build.make applications/CMakeFiles/sensor.dir/sensor.c.i
.PHONY : sensor.c.i

sensor.s: sensor.c.s

.PHONY : sensor.s

# target to generate assembly for a file
sensor.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/sensor.dir/build.make applications/CMakeFiles/sensor.dir/sensor.c.s
.PHONY : sensor.c.s

tesla.o: tesla.c.o

.PHONY : tesla.o

# target to build an object file
tesla.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/tesla.dir/build.make applications/CMakeFiles/tesla.dir/tesla.c.o
.PHONY : tesla.c.o

tesla.i: tesla.c.i

.PHONY : tesla.i

# target to preprocess a source file
tesla.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/tesla.dir/build.make applications/CMakeFiles/tesla.dir/tesla.c.i
.PHONY : tesla.c.i

tesla.s: tesla.c.s

.PHONY : tesla.s

# target to generate assembly for a file
tesla.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/tesla.dir/build.make applications/CMakeFiles/tesla.dir/tesla.c.s
.PHONY : tesla.c.s

teslaCarlo.o: teslaCarlo.c.o

.PHONY : teslaCarlo.o

# target to build an object file
teslaCarlo.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/teslaCarlo.dir/build.make applications/CMakeFiles/teslaCarlo.dir/teslaCarlo.c.o
.PHONY : teslaCarlo.c.o

teslaCarlo.i: teslaCarlo.c.i

.PHONY : teslaCarlo.i

# target to preprocess a source file
teslaCarlo.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/teslaCarlo.dir/build.make applications/CMakeFiles/teslaCarlo.dir/teslaCarlo.c.i
.PHONY : teslaCarlo.c.i

teslaCarlo.s: teslaCarlo.c.s

.PHONY : teslaCarlo.s

# target to generate assembly for a file
teslaCarlo.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/teslaCarlo.dir/build.make applications/CMakeFiles/teslaCarlo.dir/teslaCarlo.c.s
.PHONY : teslaCarlo.c.s

wall.o: wall.c.o

.PHONY : wall.o

# target to build an object file
wall.c.o:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/wall.dir/build.make applications/CMakeFiles/wall.dir/wall.c.o
.PHONY : wall.c.o

wall.i: wall.c.i

.PHONY : wall.i

# target to preprocess a source file
wall.c.i:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/wall.dir/build.make applications/CMakeFiles/wall.dir/wall.c.i
.PHONY : wall.c.i

wall.s: wall.c.s

.PHONY : wall.s

# target to generate assembly for a file
wall.c.s:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(MAKE) -f applications/CMakeFiles/wall.dir/build.make applications/CMakeFiles/wall.dir/wall.c.s
.PHONY : wall.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... teslaCarlo"
	@echo "... tesla"
	@echo "... sensor"
	@echo "... wall"
	@echo "... sensor.o"
	@echo "... sensor.i"
	@echo "... sensor.s"
	@echo "... tesla.o"
	@echo "... tesla.i"
	@echo "... tesla.s"
	@echo "... teslaCarlo.o"
	@echo "... teslaCarlo.i"
	@echo "... teslaCarlo.s"
	@echo "... wall.o"
	@echo "... wall.i"
	@echo "... wall.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/marigov/Documents/Simulator_Release_170110/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

